In [15]:
# 1-Import
import numpy as np

In [165]:
# 2- Create a numpy 5X5 matrix with ones at the borders & zeros inside.
s=np.zeros((5,5))
s[0,:]=1
s[4,:]=1
s[:,4]=1
s[:,0]=1
s.astype(int)

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [167]:
#3-Create a 5X5 matrix where the first diagonal = 1, while the second diagonal = 2, while other values=3.

matrix = np.full((5, 5), 3, dtype=int)

for i in range(5):
    matrix[i, i] = 1

for i in range(5):
    matrix[i, 4 - i] = 2

print(matrix)


[[1 3 3 3 2]
 [3 1 3 2 3]
 [3 3 2 3 3]
 [3 2 3 1 3]
 [2 3 3 3 1]]


In [208]:
# 4- Consider representing parameters & biases of  the following system of linear algebra using matrices & Vectors:
# 5x1 + 3x2 = 20
# 3x1 - 6x2 =10


# Coefficient matrix A
A = np.array([[5, 3],
              [3, -6]])

# Constant vector B
B = np.array([20, 10])
C = np.array(["X1","X2"])

# Solve for X (x1, x2)
#B=A.dot(C)



In [218]:
#5- Create two matrices with any values you like and stack them vertically
A = np.array([[5, 3],
              [3, -6]])

B = np.array([[1, 4],
              [7, -8]])
C=np.append(A,B,axis=0)
C

array([[ 5,  3],
       [ 3, -6],
       [ 1,  4],
       [ 7, -8]])